services:
  mysql:
    image: mysql:8.0
    container_name: student_management_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: student_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: db@032025
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql  # Map the local folder to container storage

volumes:
  db_data:                                # Define a named volume as part of the mapping
